import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { config } from './config.js';
import { authRouter } from './routes/auth.js';
import { cardsRouter } from './routes/cards.js';
import { publicRouter } from './routes/public.js';
import { errorHandler, notFound } from './middleware/errors.js';

const root = dirname(fileURLToPath(import.meta.url));
export const app = express();
app.disable('x-powered-by');
app.use(helmet({ contentSecurityPolicy: false, crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: config.PUBLIC_ORIGIN, methods: ['GET', 'POST'] }));
app.use(express.json({ limit: '2mb' }));
app.use('/api', rateLimit({ windowMs: 60_000, limit: 180, standardHeaders: 'draft-7', legacyHeaders: false }));
app.use('/api/auth', rateLimit({ windowMs: 15 * 60_000, limit: 30 }), authRouter);
app.use('/api/cards', cardsRouter);
app.use('/api', publicRouter);
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
app.use(express.static(join(root, '../public'), { maxAge: '1h' }));
app.get('/colecao/:username', (req, res) => res.sendFile(join(root, '../public/index.html')));
app.use('/api', notFound);
app.get('*splat', (req, res) => res.redirect('/colecao/duelista'));
app.use(errorHandler);
